### ISSUE TITLE
Dataclass not installed?

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/np_codeocean#14]
After installing np_codeocean in a clean environment and running `upload`, I received the following error.

```
Traceback (most recent call last):
  File "C:\Users\carter.peene\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\carter.peene\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\carter.peene\Desktop\Projects\openscope_upload\upload_env\Scripts\upload.exe\__main__.py", line 4, in <module>
  File "C:\Users\carter.peene\Desktop\Projects\np_codeocean\src\np_codeocean\__init__.py", line 2, in <module>
    from np_codeocean.upload import *
  File "C:\Users\carter.peene\Desktop\Projects\np_codeocean\src\np_codeocean\upload.py", line 7, in <module>
    import dataclass
ModuleNotFoundError: No module named 'dataclass'
```

**Comment by rcpeene** [comment]
Probably something wrong with my environment; not sure but not fixable here
